Repository owncloud/diagnostics, pull requests merged in 2020-04, with the labels that each got.

#56 [Tests-Only] Bump phan 2.7
  .drone.star
  .phan/config.php
  vendor-bin/phan/composer.json
Labels: QA-team

#57 Drop PHP 7.1
  .drone.star
  composer.json
  composer.lock
Labels: 3 - To Review, QA-team

#58 [Tests-Only] Implement phpunit v8
  .gitignore
  tests/unit/DiagnosticsTest.php
  tests/unit/Log/LogTest.php
  tests/unit/Panels/AdminTest.php
Labels: 4 - To release, QA-team

#59 Adjust drone pipelines for PHP 7.4
  .drone.star
Labels: 3 - To Review, QA-team
